name: PR Build
on: [ pull_request ]
jobs:
  Lint-check:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Detekt check
        run: ./gradlew detekt
      - name: Generate Kover report
        run: ./gradlew koverXmlReportDebug
      - name: Parse Kover Report
        uses: mi-kas/kover-report@v1.9
        with:
          path: ${{ github.workspace }}/app/build/reports/kover/reportDebug.xml
          token: ${{ secrets.KOVER_TOKEN }}
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: LINE
